version: 2
updates:
  # Github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"
  
  # Root Go module
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  # Test scenario Go module
  - package-ecosystem: "gomod"
    directory: "provider/scenario"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"
